### ISSUE TITLE
is it smth only for xbox ?

### ISSUE THREAD

**Issue by roberto68** [brandtabbott/spotify-server#4]
cause I installed node v 0.10.24 and it is not working util.js is missing in the /lib (though in the source there's no util.js ) but I'm gettin plenty unsigned/signed warnings .... what is needed to update this, only replace verisons in package.json? or some code change too? and why there's remove node gyp ?

**Comment by brandtabbott** [comment]
@roberto68 Sorry for the delayed response.  I haven't updated this in a while.  Let me do some updates and get back to you.

**Comment by brandtabbott** [comment]
@roberto68 This works now with node version 4.4.0 - I tried with an older version (0.10.10) on a different machine and it fails for some reason during playback.
